[tools]
python = "3.12"

[env]
_.python.venv = { path = ".venv", create = true } # create the venv if it doesn't exist
_.file = ".env.yaml"

[hooks]
enter = "echo 'Welcome to the template project'"

[tasks.app]
run = 'uv run python app.py'

[tasks.docs]
run = 'cd docs; uv run mkdocs serve'

[tasks.test]
run = 'uv run pytest'

[tasks.pyright]
run = 'uv run pyright'

[tasks.chat]
run = 'uv run chainlit run src/app.py -w'

[tasks.server]
run = 'uv run python src/mcp_server.py'

[tasks.dev-server]
run = 'uv run mcp dev src/mcp_server.py'
